export const LOAD_COURSES_SUCCESS='LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS='LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';

export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS';
export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS';
export const UPDATE_PLAYERS_SUCCESS = 'UPDATE_PLAYERS_SUCCESS';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const UPDATE_WORDS_SUCCESS = 'UPDATE_WORDS_SUCCESS';


export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS';
export const UPDATE_ANSWERS_SUCCESS = 'UPDATE_ANSWERS_SUCCESS';
export const LOAD_ANSWERS_SUCCESS = 'LOAD_ANSWERS_SUCCESS';

export const ADD_MYSELF_SUCCESS = 'ADD_MYSELF_SUCCESS';
