export const LOAD_COURSES_SUCCSESS='LOAD_COURSES_SUCCSESS';
export const LOAD_AUTHORS_SUCCSESS='LOAD_AUTHORS_SUCCSESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const LOAD_MESSAGES_SUCCSESS = 'LOAD_MESSAGES_SUCCSESS';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS';
export const LOAD_PLAYERS_SUCCSESS = 'LOAD_PLAYERS_SUCCSESS';
export const UPDATE_PLAYERS_SUCCESS = 'UPDATE_PLAYERS_SUCCESS';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const UPDATE_WORDS_SUCCESS = 'UPDATE_WORDS_SUCCESS';

